### ISSUE TITLE
Improve keyword metadata

### ISSUE THREAD

**Issue by pascalin** [PhilosophyHubio/kw_extractor#2]
In addition to suggested keywords, JSON output should include **zotero_key** as metadata, that way it is possible to relate extracted keywords with the corresponding Zotero item. This information can be obtained from the attachment's containing folder name.

**Comment by ipardogranillo** [comment]
This is related to https://github.com/PhilosophyHubio/kw_extractor/issues/1 and it's relatively easy to include, so it should go second; or rather, in parallel.

**Comment by ipardogranillo** [comment]
This was already solved as shown with the given output in https://github.com/PhilosophyHubio/kw_extractor/issues/1

**Comment by pascalin** [comment]
This does not seem to be working yet. At least, when I ran the script I got the PDF's file name as ID. This is surely related to the script not preserving the zotero_key when extracting the PDF text content inside the 'corpora' directory.
