### ISSUE TITLE
tree_reader.sh shouldn't create any files inside Zotero storage path

### ISSUE THREAD

**Issue by pascalin** [PhilosophyHubio/kw_extractor#3]
Following [UNIX's design philosophy](https://en.wikipedia.org/wiki/Unix_philosophy) it would be better to use a temporary location for writing PDFs' extracted text and to write JSON output with metadata to standard output.

**Comment by ipardogranillo** [comment]
this should be the third issue to solve, as it involves something different than json processing, but it shouldn't be too difficult.

**Comment by ipardogranillo** [comment]
This was already solved by creating a folder (the code will create it if non-existent) inside kw_extractor folder. This folder was added to the .gitignore file and tree_reader.sh now works directly with the Zotero/storage rather than the test_storage folder.

**Comment by ipardogranillo** [comment]
My mistake, this issue is still open as txt files are created within Zotero storage path

**Comment by ipardogranillo** [comment]
corpora/ folder was created in order to store all text files; treereader.sh takes care of creating it along with keywords/ in case they haven't been created yet; corpora/ was also added to .gitignore
